[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:flaskapp]
command=python3 /app/app.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/flaskapp.out.log
stderr_logfile=/var/log/flaskapp.err.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB

[program:metadataservice]
command=python3 /app/metadata_service.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/metadata.out.log
stderr_logfile=/var/log/metadata.err.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
